### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by sturfee-petrl** [matthieudolci/docker-gvm#1]
It will be excellent if there would be some instruction about how to use it. 
I mean:
1. I copied your run commands to my own dockerfile
2. > /bin/bash: gvm: command not found
3. If I do before
 > source /bin/bash: /root/.gvm/scripts/gvm

It still doesn't work
> /bin/bash: gvm: command not found

4. If I do
>  /root/.gvm/scripts/gvm listall

I have 
>/bin/bash: /root/.gvm/scripts/gvm: Permission denied

**Comment by matthieudolci** [comment]
Hi @sturfee-petrl ,

Just made a change to have an entrypoint. The previous version was only working when doing a `docker exec -it matthieudolci/docker-gvm /bin/bash`

Let me know if it works for you ;-)

**Comment by sturfee-petrl** [comment]
I was trying to use it as intermediate step in my container)

Thank you! For fast response!
